### PR TITLE
SND Role Impersonation

### PR DESCRIPTION
**Pull request by labkey-martyp**
#### Rationale
Override the new behavior of role impersonation to allow non-container based permissions checks.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/5729

#### Changes
* Use hasAllPermissions instead of hasPermission in SNDSecurityManager
* Pass in roles to hasAllPermissions when doing Role Impersonation
* Add better error handling in SND test

### CODE REVIEW

**Comment by labkey-adam** [comment]
@labkey-martyp using an `ImpersonationContext` (directly or indirectly) does seem like the right approach. Would using `LimitedUser` or `ElevatedUser` meet your requirements? If so, this would be a more standard pattern.

**Comment by labkey-adam** [comment]
Actually, my preferred option would be to call `SecurityManager.hasAllPermissions()` and pass in the roles as the contextualRoles parameter (empty in the non-impersonating case). Using contextual roles is usually the recommended way to do this sort of thing... no need for a new class, new user, etc.

**Review by labkey-adam — CHANGES_REQUESTED** [review]
See comments... I think this can be simplified significantly. This is a job for contextual roles.

**Comment by labkey-martyp** [comment]
> See comments... I think this can be simplified significantly. This is a job for contextual roles.

Thanks @labkey-adam I'll check that out

**Comment by labkey-martyp** [comment]
> > See comments... I think this can be simplified significantly. This is a job for contextual roles.
> 
> Thanks @labkey-adam I'll check that out

@labkey-adam Ok refactored to use hasAllPermissions. Please review when you're available.

**Review by labkey-adam — APPROVED** [review]

**Pull request merged**
